# Generated by Django 4.2.7 on 2023-11-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="alt",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.IntegerField(default=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="image_title",
            field=models.CharField(default=300, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
