# Generated by Django 4.2.7 on 2023-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_cms", "0003_title_css_class_title_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="title",
            name="css_class",
        ),
        migrations.AddField(
            model_name="component",
            name="css_class",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
