# Generated by Django 4.2.7 on 2023-11-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("easy_cms", "0004_remove_title_css_class_component_css_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="easy_cms.page",
            ),
        ),
    ]
