# Generated by Django 4.2.7 on 2023-11-04 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("easy_cms", "0006_page_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["order"]},
        ),
    ]
