# Generated by Django 4.2.7 on 2023-11-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("easy_cms", "0009_page_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParagraphTwoCols",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="easy_cms.component",
                    ),
                ),
                ("col_1", models.TextField()),
                ("col_2", models.TextField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("easy_cms.component",),
        ),
    ]
