# Generated by Django 4.2.7 on 2023-11-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_cms", "0010_paragraphtwocols"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="height",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="width",
            field=models.IntegerField(blank=True),
        ),
    ]
