# Generated by Django 4.2.7 on 2023-11-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("easy_cms", "0012_alter_image_height_alter_image_image_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="image",
            name="height",
            field=models.IntegerField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="image",
            name="width",
            field=models.IntegerField(blank=True, default=""),
        ),
    ]
